- hosts: master
  become: yes
  tasks:
    - name: create nginx namespace
      become: yes
      become_user: ubuntu
      shell: kubectl get namespaces nginx || kubectl create namespace nginx

    - name: add stable helm repo
      become: yes
      become_user: ubuntu
      shell: helm repo add stable https://kubernetes-charts.storage.googleapis.com/

    - name: install nginx
      become: yes
      become_user: ubuntu
      shell: helm upgrade --install nginx stable/nginx-ingress --set controller.service.type=NodePort --namespace nginx

    - name: create openvpn namespace
      become: yes
      become_user: ubuntu
      shell: kubectl get namespaces openvpn || kubectl create namespace openvpn

    - name: install openvpn
      become: yes
      become_user: ubuntu
      shell: helm upgrade --install openvpn stable/openvpn --set persistence.enabled=false,service.type=NodePort,openvpn.keystoreSecret=openvpn-keystore-secret --namespace openvpn
