- hosts: master
  become: yes
  tasks:
    - name: create service namespace
      become: yes
      become_user: ubuntu
      shell: kubectl create namespace services

    - name: add helm repo
      become: yes
      become_user: ubuntu
      shell: helm repo add stable https://kubernetes-charts.storage.googleapis.com/

    - name: install nginx
      become: yes
      become_user: ubuntu
      shell: helm upgrade --install nginx stable/nginx-ingress --namespace services
