- hosts: master
  become: yes
  tasks:
    - name: add nginx helm repo
      become: yes
      become_user: ubuntu
      shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: install nginx
      become: yes
      become_user: ubuntu
      shell: helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --set controller.service.type=ClusterIP,controller.hostNetwork=true,controller.dnsPolicy=ClusterFirstWithHostNet,controller.kind=DaemonSet,controller.extraArgs.report-node-internal-ip-address=true --namespace ingress-nginx --create-namespace

    - name: add stable helm repo
      become: yes
      become_user: ubuntu
      shell: helm repo add stable https://charts.helm.sh/stable

    - name: install openvpn
      become: yes
      become_user: ubuntu
      shell: helm upgrade --install openvpn stable/openvpn --set persistence.enabled=false,service.type=NodePort,openvpn.keystoreSecret=openvpn-keystore-secret --namespace openvpn --create-namespace

    - name: create cert-manager namespace
      become: yes
      become_user: ubuntu
      shell: kubectl get namespaces cert-manager || kubectl create namespace cert-manager

    - name: install cert-manager
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml

    - name: add metric server helm repo
      become: yes
      become_user: ubuntu
      shell: helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/

    - name: install metrics server
      become: yes
      become_user: ubuntu
      shell: helm upgrade --install metric-server metrics-server/metrics-server --set args={--kubelet-insecure-tls\,--kubelet-preferred-address-types=InternalIP\,--metric-resolution=30s},hostNetwork.enabled=true --namespace kube-system

    - name: add keda helm repo
      become: yes
      become_user: ubuntu
      shell: helm repo add kedacore https://kedacore.github.io/charts

    - name: install keda
      become: yes
      become_user: ubuntu
      shell: helm upgrade --install keda kedacore/keda --namespace keda --create-namespace

    - name: install dashboard
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

    - name: configure dashboard
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f ../resources/configuration/dashboard-adminuser.yaml
