- hosts: master
  become: yes
  tasks:
    - name: create .openvpn secrets directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/openvpn/secrets
        state: directory
        mode: 0755

    - name: copy server.key
      copy:
        src: ../resources/openvpn-secrets/server.key
        dest: /home/ubuntu/openvpn/secrets/server.key
        owner: ubuntu
        mode: 0755

    - name: copy ca.crt
      copy:
        src: ../resources/openvpn-secrets/ca.crt
        dest: /home/ubuntu/openvpn/secrets/ca.crt
        owner: ubuntu
        mode: 0755

    - name: copy server.crt
      copy:
        src: ../resources/openvpn-secrets/server.crt
        dest: /home/ubuntu/openvpn/secrets/server.crt
        owner: ubuntu
        mode: 0755

    - name: copy dh.pem key
      copy:
        src: ../resources/openvpn-secrets/dh.pem
        dest: /home/ubuntu/openvpn/secrets/dh.pem
        owner: ubuntu
        mode: 0755

    - name: create openvpn namespace
      become: yes
      become_user: ubuntu
      shell: kubectl get namespaces openvpn || kubectl create namespace openvpn
      
    - name: create openvpn secrets
      become: yes
      become_user: ubuntu
      shell: kubectl create secret generic openvpn-keystore-secret --from-file=/home/ubuntu/openvpn/secrets/server.key --from-file=/home/ubuntu/openvpn/secrets/ca.crt --from-file=/home/ubuntu/openvpn/secrets/server.crt --from-file=/home/ubuntu/openvpn/secrets/dh.pem --namespace openvpn



