- hosts: master
  become: yes
  tasks:
    - name: disable ufw
      become: yes
      shell: sudo ufw disable

    - name: reset ufw
      become: yes
      shell: echo "y" | sudo ufw reset

    - name: enable ports
      become: yes
      shell: |
        sudo ufw allow ssh
        sudo ufw allow from master
        sudo ufw allow from worker1
        sudo ufw allow from worker2

    - name: enable ufw
      become: yes
      shell: echo "y" | sudo ufw enable

- hosts: workers
  become: yes
  tasks:
    - name: disable ufw
      become: yes
      shell: sudo ufw disable

    - name: reset ufw
      become: yes
      shell: echo "y" | sudo ufw reset

    - name: enable ports
      become: yes
      shell: |
        sudo ufw allow http
        sudo ufw allow https
        sudo ufw allow ssh
        sudo ufw allow 30000:32767/tcp
        sudo ufw allow from master
        sudo ufw allow from worker1
        sudo ufw allow from worker2

    - name: enable ufw
      become: yes
      shell: echo "y" | sudo ufw enable
