- hosts: master
  become: yes
  tasks:
    - name: disable ufw
      shell: sudo ufw disable

    - name: reset ufw
      shell: echo "y" | sudo ufw reset

    - name: enable ports
      shell: |
        sudo ufw allow ssh
        sudo ufw allow from 62.171.176.59
        sudo ufw allow from 62.171.177.253
        sudo ufw allow from 62.171.177.254

    - name: enable ufw
      shell: echo "y" | sudo ufw enable

- hosts: workers
  become: yes
  tasks:
    - name: Disable UFW
      shell: sudo ufw disable

    - name: Reset UFW
      shell: echo "y" | sudo ufw reset

    - name: Allow SSH and internal traffic
      shell: |
        sudo ufw allow ssh
        sudo ufw allow from 62.171.176.59
        sudo ufw allow from 62.171.177.253
        sudo ufw allow from 62.171.177.254

    - name: Allow OpenVPN NodePort
      shell: sudo ufw allow 32085/tcp

    - name: Allow Cloudflare IPv4 for HTTP/HTTPS
      shell: |
        for ip in $(curl -s https://www.cloudflare.com/ips-v4); do
          sudo ufw allow from $ip to any port 80 proto tcp
          sudo ufw allow from $ip to any port 443 proto tcp
        done

    - name: Allow Cloudflare IPv6 for HTTP/HTTPS
      shell: |
        for ip in $(curl -s https://www.cloudflare.com/ips-v6); do
          sudo ufw allow from $ip to any port 80 proto tcp
          sudo ufw allow from $ip to any port 443 proto tcp
        done

    - name: Enable UFW
      shell: echo "y" | sudo ufw enable
