- hosts: master
  become: yes
  tasks:
    - name: disable ufw
      become: yes
      shell: sudo ufw disable

    - name: reset ufw
      become: yes
      shell: echo "y" | sudo ufw reset

    - name: enable ports
      become: yes
      shell: |
        sudo ufw allow ssh
        sudo ufw allow from 62.171.176.59
        sudo ufw allow from 62.171.177.253
        sudo ufw allow from 62.171.177.254

    - name: enable ufw
      become: yes
      shell: echo "y" | sudo ufw enable

- hosts: workers
  become: yes
  tasks:
    - name: disable ufw
      become: yes
      shell: sudo ufw disable

    - name: reset ufw
      become: yes
      shell: echo "y" | sudo ufw reset

    - name: enable ports
      become: yes
      shell: |
        sudo ufw allow http
        sudo ufw allow https
        sudo ufw allow ssh
        sudo ufw allow 32085/tcp
        sudo ufw allow from 62.171.176.59
        sudo ufw allow from 62.171.177.253
        sudo ufw allow from 62.171.177.254

    - name: enable ufw
      become: yes
      shell: echo "y" | sudo ufw enable
